# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GITHUB\projetoSCO\TELAS.PY\CADASTRAR.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 538)
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(-10, -30, 741, 571))
        self.background.setStyleSheet("background-color: rgb(170, 197, 255);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.img_login_T2 = QtWidgets.QLabel(Dialog)
        self.img_login_T2.setGeometry(QtCore.QRect(300, 10, 131, 111))
        self.img_login_T2.setStyleSheet("image: url(:/img/USUARIO.png);")
        self.img_login_T2.setText("")
        self.img_login_T2.setObjectName("img_login_T2")
        self.Usuario = QtWidgets.QLabel(Dialog)
        self.Usuario.setGeometry(QtCore.QRect(120, 140, 141, 51))
        self.Usuario.setObjectName("Usuario")
        self.C_usuario = QtWidgets.QLineEdit(Dialog)
        self.C_usuario.setGeometry(QtCore.QRect(270, 150, 221, 31))
        self.C_usuario.setObjectName("C_usuario")
        self.email = QtWidgets.QLabel(Dialog)
        self.email.setGeometry(QtCore.QRect(110, 190, 141, 51))
        self.email.setObjectName("email")
        self.C_email = QtWidgets.QLineEdit(Dialog)
        self.C_email.setGeometry(QtCore.QRect(270, 200, 221, 31))
        self.C_email.setObjectName("C_email")
        self.Senha = QtWidgets.QLabel(Dialog)
        self.Senha.setGeometry(QtCore.QRect(190, 240, 91, 41))
        self.Senha.setObjectName("Senha")
        self.ConfirmarSenha = QtWidgets.QLabel(Dialog)
        self.ConfirmarSenha.setGeometry(QtCore.QRect(90, 280, 171, 51))
        self.ConfirmarSenha.setObjectName("ConfirmarSenha")
        self.C_senha = QtWidgets.QLineEdit(Dialog)
        self.C_senha.setGeometry(QtCore.QRect(270, 250, 221, 31))
        self.C_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.C_senha.setObjectName("C_senha")
        self.C_ConfirmarSenha = QtWidgets.QLineEdit(Dialog)
        self.C_ConfirmarSenha.setGeometry(QtCore.QRect(270, 300, 221, 31))
        self.C_ConfirmarSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.C_ConfirmarSenha.setObjectName("C_ConfirmarSenha")
        self.B_Cadastrar = QtWidgets.QPushButton(Dialog)
        self.B_Cadastrar.setGeometry(QtCore.QRect(310, 370, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_Cadastrar.sizePolicy().hasHeightForWidth())
        self.B_Cadastrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.B_Cadastrar.setFont(font)
        self.B_Cadastrar.setStyleSheet("background-color: rgb(130, 217, 210);\n"
"color: rgb(255, 255, 255);")
        self.B_Cadastrar.setIconSize(QtCore.QSize(16, 16))
        self.B_Cadastrar.setAutoRepeatDelay(300)
        self.B_Cadastrar.setAutoRepeatInterval(100)
        self.B_Cadastrar.setObjectName("B_Cadastrar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Usuario.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Nome Usuário:</span></p></body></html>"))
        self.email.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">E-mail Usuário:</span></p></body></html>"))
        self.Senha.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Senha:</span></p></body></html>"))
        self.ConfirmarSenha.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Confirmar Senha:</span></p></body></html>"))
        self.B_Cadastrar.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Cadastrar</span></p></body></html>"))
        self.B_Cadastrar.setText(_translate("Dialog", "Cadastrar"))
import sourcee_rc
